modLoader="javafml"
loaderVersion="[47,)"
license="Apache License version 2.0"

[[mods]]
modId="amamma"
version="1.1.0"
displayName="Amamma"
displayURL="https://kamivt.dev"
logoFile="logo.png"
credits="Amamma PNG by: https://x.com/holykoshi"
authors="Meow"
description="Adds that silly Meowderator to your world! (She will ban you)"


[[dependencies.amamma]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"